<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AccountingSystem.Core/AccountingSystem.Core.csproj" />
    <ProjectReference Include="../AccountingSystem.Data/AccountingSystem.Data.csproj" />
  </ItemGroup>

</Project>
